### ISSUE TITLE
Linux build support

### ISSUE THREAD

**Issue by dabrain34** [segfaultxavi/galaxies#1]

**Comment by dabrain34** [comment]
[CMakeLists.txt](https://github.com/segfaultxavi/galaxies/files/1629867/CMakeLists.txt)

**Comment by segfaultxavi** [comment]
Thanks a lot!
Added in 339c754e2d2862f5780588aaea3c0dd3095c4d8b

I had to change the TTF dependency from sdl_ttf to SDL2_ttf. Does this work for you?
