### ISSUE TITLE
Exit with TTF_OpenFontRW error using Linux build

### ISSUE THREAD

**Issue by dabrain34** [segfaultxavi/galaxies#2]
INFO: TTF_OpenFontRW: Can't write to read-only memory

**Comment by segfaultxavi** [comment]
Can you tell me you OS and versions of sdl2 and SDL2_ttf?
I have never seen this neither on Windows 10, Ubuntu16.04 or Android, with sdl2 (2.0.4, 2.0.5 and 2.0.7) and SDL2_ttf 2.0.14.

**Comment by dabrain34** [comment]
Ok so I found out that i was using the wrong version of libsdl_ttf. 
So i installed ( you should add this hint in cmake or Readme) libsdl2-ttf-dev and libsdl2-dev and now the game is running well.

**Comment by segfaultxavi** [comment]
Will try that. But I am more suspicious of the SDL and SDL_TTF versions... do you know those?

**Comment by segfaultxavi** [comment]
Works here on Ubuntu 17.04 64bits with SDL 2.0.5 and SDL_TTF 2.0.14

**Comment by dabrain34** [comment]
Works here also. You might have missed my comment update ;)

**Comment by segfaultxavi** [comment]
Haha, yeah, I missed it.

Sorry, I have never user CMake before. What do I need to add to CMakeLists.txt ?

**Comment by dabrain34** [comment]
You can put a message in CMakeList.txt or you can create a Readme in your project tree explaining the linux build dependencies (  libsdl2-ttf-dev & libsdl2-dev)

**Comment by segfaultxavi** [comment]
I still do not understand this completely. You didn't have libsdl2-ttf-dev installed but CMake allowed you to continue?

**Comment by dabrain34** [comment]
Of course not! But you updated the cmake file to use the right pc file and i was using the one i thought i have to use ;)
So with your CMakeList.txt, cmake was failing until i got the right pc files ...

**Comment by segfaultxavi** [comment]
Ooookkkk, so everything's fine now :)

**Comment by dabrain34** [comment]
Exactly, except you have to update either the doc or the CMakeList.txt to inform about that. But it is up to you ! 🥇

**Comment by segfaultxavi** [comment]
Added to the TODO so I don't forget :)
